# Python Giriş

In [1]:
5*5


25

In [2]:
100+200

300

In [3]:
12%5

2

In [7]:
yas=int(input("yasinizi giriniz:"))

yasinizi giriniz:50


In [6]:
yas*5

'6060606060'

In [8]:
yas/10

5.0

In [9]:
yas*5


250

In [10]:
yeniString="aslisesli"


In [16]:
yeniString[2:5]

'lis'

In [3]:
ilk_degisken=input()
print("Dışarıdan alınan veri: "+ilk_degisken+" verinin tipi "+str(type(ilk_degisken)))

 52


Dışarıdan alınan veri: 52 verinin tipi <class 'str'>


In [4]:
type(ilk_degisken)


str

In [5]:
ad=input("adınızı giriniz:")
yas=int(input("yasınızı giriniz:"))
print("kullanıcının adı {} kullanıcın yası {}".format(ad,yas))

adınızı giriniz: Asli
yasınızı giriniz: 23


kullanıcının adı Asli kullanıcın yası23


In [7]:
print("kullanıcının adı %s kullanıcın yası %d" %(ad,yas))

kullanıcının adı Asli kullanıcın yası 23


In [13]:
int_1=5
float_1=float(5)
complex_1=complex(3,4)
complex_1


(3+4j)

In [11]:
sayi=4
sayi

4

In [30]:
a= "aslisesli"
print(a.find("l"))
print(a.rfind("k"))
#a.rfind()

2
-1


In [33]:
txt="i like fruit"
txt.replace("like", "hate")

'i hate fruit'

In [34]:
txt.zfill(25)

'0000000000000i like fruit'

In [37]:
listem=[10,20,30,40,50]
listem.count(10)

1

In [40]:
stringlistem=['asli','sesli']
stringlistem .append(5)


In [41]:
stringlistem

['asli', 'sesli', 5]

In [42]:
nestedlist=[1, 2.5, 6, [7,'z']]
sonuc = nestedlist[3]


In [43]:
sonuc[1]

'z'

In [45]:
sonuc  = nestedlist[3][1]

In [46]:
sonuc

'z'

In [47]:
karmasikliste=[[1,2,['a','b'],40],50,[35,65],[3,['z']]]
deger=karmasikliste[3][1]

In [48]:
deger

['z']

In [49]:
deger=karmasikliste[1]

In [50]:
deger

50

In [51]:
deger=karmasikliste[0][2][0]

In [52]:
deger

'a'

In [54]:
len(listem)

5

In [1]:
kahraman="batman"

In [3]:
if kahraman=="batman":
   print("dogru")

dogru


In [4]:
x=5

In [5]:
if x < 6:
    print(" x küçük 6")

 x küçük 6


In [6]:
yeniListe=[(1,2),(3,4),(5,6)]

In [7]:
for rakam in yeniListe:
    if rakam%2==0:
        print(rakam)
    

2
4
6


In [23]:
yeniDegisken=0

In [24]:
while yeniDegisken<15:
   # print("yenidediskenin güncel degeri {} ".format(yeniDegisken))
     #print("yenidediskenin güncel degeri:" + str(yeniDegisken))
     print(f"yenidediskenin güncel degeri: {yeniDegisken}")
     yeniDegisken=yeniDegisken+1

yenidediskenin güncel degeri: 0
yenidediskenin güncel degeri: 1
yenidediskenin güncel degeri: 2
yenidediskenin güncel degeri: 3
yenidediskenin güncel degeri: 4
yenidediskenin güncel degeri: 5
yenidediskenin güncel degeri: 6
yenidediskenin güncel degeri: 7
yenidediskenin güncel degeri: 8
yenidediskenin güncel degeri: 9
yenidediskenin güncel degeri: 10
yenidediskenin güncel degeri: 11
yenidediskenin güncel degeri: 12
yenidediskenin güncel degeri: 13
yenidediskenin güncel degeri: 14


In [25]:
range(5)

range(0, 5)

In [26]:
list(range(5))

[0, 1, 2, 3, 4]

In [28]:
for i in list(range(10)):
    print(i)
    

0
1
2
3
4
5
6
7
8
9


In [29]:
list(range(2,20,2))

[2, 4, 6, 8, 10, 12, 14, 16, 18]

In [30]:
for (index,numara) in enumerate(list(range(5,15))):
    print(index,numara)

0 5
1 6
2 7
3 8
4 9
5 10
6 11
7 12
8 13
9 14


In [31]:
from random import randint

In [33]:
randint(0,50)

13

In [37]:
yeniListe=list(range(0,10))

In [38]:
yeniListe

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
yeniString="asli sesli"

In [40]:
yeniListe=[eleman for eleman in yeniString]

In [41]:
yeniListe

['a', 's', 'l', 'i', ' ', 's', 'e', 's', 'l', 'i']

In [46]:
digerListe=[numara*5 for numara in list(range(0,5))]

In [47]:
digerListe

[0, 5, 10, 15, 20]

In [48]:
def toplama(num1,num2):
    sonuc = num1+num2
    print(sonuc)

In [49]:
toplama(10,20)

30


In [50]:
def keywordarg(**kwargs):
    return kwargs

In [53]:
keywordarg(muz=100, elma=200)

{'muz': 100, 'elma': 200}

In [1]:
"_Python_".strip("_")

'Python'

In [2]:
print("uzaya", "git", sep = "**")

uzaya**git


In [3]:
A = []
B = []

for i in [1,"a",12,"b"]:
    if type(i) == int:
        B.append(i)
    else:
        A.append(i)

A[1]

'b'

In [4]:
a = 5
b = 10
c = a*b
c

50

In [5]:
sayilar = [10,20,30,40]
 
for i in sayilar:
    if i == 30:
        continue
    print(i)

10
20
40


In [6]:
a = "bu uzun bir metindir"
a[8]

'b'

In [7]:
def islem(x,y):
    A = [x,y]
    return A[0] + A[1]

islem(1,3)

4

In [8]:
a = "bu uzun bir metindir"
a[2:5]

' uz'

In [9]:
degisken = 4
degisken*degisken

16

In [11]:
A = []

for i in [1,2,3,4]:
    A.append(i)

A[0]

1

In [12]:
liste=["asli","sesli"]

In [13]:
liste.append("sesliii")

In [14]:
liste

['asli', 'sesli', 'sesliii']

In [16]:
liste=liste+["aslii"]

In [17]:
liste

['asli', 'sesli', 'sesliii', 'aslii']

In [18]:
liste.remove("asli")

In [19]:
liste

['sesli', 'sesliii', 'aslii']

In [23]:
del liste[0]

In [24]:
liste

['sesliii', 'aslii']

In [27]:
sozluk={"REG": "regresyon","LOJ":"lojistik","CART":"classicitaion"}

In [28]:
sozluk

{'REG': 'regresyon', 'LOJ': 'lojistik', 'CART': 'classicitaion'}

In [30]:
sozluk.keys()

dict_keys(['REG', 'LOJ', 'CART'])

In [31]:
sozluk.values()

dict_values(['regresyon', 'lojistik', 'classicitaion'])

In [32]:
set1 = set([5,7,9])
set2 = set([5,6,7])
set1.union(set2)

{5, 6, 7, 9}

In [33]:
liste = ["A","B","C"] 

In [34]:

liste[0] = "D"

In [35]:
liste

['D', 'B', 'C']

In [36]:
set1 = set([5,7,9])
set2 = set([5,6,7])
set1.difference(set2)

{9}

In [37]:
liste = ["a","b","c"]
liste.reverse()
print(liste)

['c', 'b', 'a']


In [38]:
liste = [1,1,2,3,4,5,1,2,1]
liste.count(1)

4

In [1]:
def kareAl(x):
    print("girilen sayinin karesi:" + str(x**2))

In [2]:
kareAl(3)

girilen sayinin karesi:9


In [3]:
def direk_hesapla(isi,nem,sarj):
    return (isi+nem)/sarj

In [4]:
direk_hesapla(25,40,50)

1.3

In [5]:
cikti=direk_hesapla(10,50,30)

In [6]:
cikti

2.0

In [9]:
x=10
y=5
def carpmaYap(x=2,y=5):
    return x*y

In [10]:
carpmaYap(2,3)

6

In [22]:
maaslar=[1000,2000,3000,4000,5000]
def maashesapla(x):
    if x<3000:
        print(x*20/100+x)
    elif x>3000:
        print(x*10/100+x)
    else:
       print("ayni")
    

    

In [27]:
for i in maaslar:
    if i==3000:
        continue
    maashesapla(i)
    

1200.0
2400.0
4400.0
5500.0


In [28]:
"_Python_".strip("_")
    

'Python'

In [29]:
"a" + "b" 

'ab'

In [30]:
"9" + 1 

TypeError: must be str, not int

In [31]:
A = []
B = []

for i in [1,"a",12,"b"]:
    if type(i) == int:
        B.append(i)
    else:
        A.append(i)

A[1]

'b'

In [32]:
ifade = "Merhaba! "
ifade.strip("")

'Merhaba! '

In [33]:
A = "*A*"    
if type(A) == str:
    A = A.strip("*")
    print(A)

A


In [34]:
sayilar = [10,20,30,40]
 
for i in sayilar:
    if i == 30:
        break
    print(i)

10
20


In [35]:
if [1,2,3,4][1] == 2:
    print("YES".lower())
else:
    print("NO")

yes


In [36]:
a = 5
b = 10
c = a*b
c

50

In [37]:
a = "bu uzun bir metindir"
a[8]

'b'

In [38]:
"10" + 2

TypeError: must be str, not int

In [39]:
A = []

for i in [1,2,3,4]:
    A.append(i)

A[0]

1

In [40]:
def harf_say(x):
    return len(x)
 
harf_say("Merhaba!")

8

In [41]:
a = [2,4,6,8]
for i in a:
    print(i**2)

4
16
36
64


In [42]:
def mesaj():
    print("Merhaba!")    
    
mesaj()

Merhaba!


In [1]:
def yazdir(metin):
    print(metin, "yazanlar")
 
yazdir("gelecegi")

gelecegi yazanlar


In [44]:
if [1,2,3,4][2] == 2:
    print("YES")
else:
    print("NO") 

NO


In [45]:
A = "*A*"    
if type(A) == str:
    A = A.strip("*")
    print(A)

A


In [46]:
def islem(x):
    if (x>10):
        return "YES"
    else:
        return x*5
 
islem(4)

20

In [47]:
A = []
B = []

for i in [1,"a",12,"b"]:
    if type(i) == int:
        B.append(i)
    else:
        A.append(i)

A[1]

'b'

In [48]:
sayilar = [10,20,30]
 
for i in sayilar:
    if i > 20:
        print(i/2)

15.0


In [49]:
def islem(x,y):
    A = [x,y]
    return A[0] + A[1]

islem(1,3) 

4

In [50]:
A = 12    
if type(A) == str:
    A = A.strip("*")
    print(A)    
else:
    A  = "*" + str(A) + "*"
    print(A.strip())

*12*


In [51]:
sayilar = [10,20,30,40]
 
for i in sayilar:
    if i == 30:
        break
    print(i)

10
20


In [52]:
liste = ["a","b","c"]
liste.reverse()
print(liste)

['c', 'b', 'a']


In [54]:
def islem(x):
    if (x<0):
        return "NO"
    else:
        x*5
 
islem(2)


In [55]:
def islem(x):
    if (x<0):
        return "NO"
    else:
        x*5
 
islem(2)

##CLASS



In [2]:
class VeriBilimci():
    print("bu bir siniftir")

bu bir siniftir


In [3]:
class VeriBilimci():
    bolum=''
    sql="EVET"
    deneyim_Yili=0

In [8]:
VeriBilimci.sql


'EVET'

In [9]:
VeriBilimci.deneyim_Yili

0

In [10]:
VeriBilimci.sql="HAYİR"

In [11]:
VeriBilimci.sql

'HAYİR'

In [12]:
VeriBilimci.sql

'HAYİR'

In [82]:
class veriBilimci():
    def __init__(self):
        self.bildigiDiller=[]
        self.bolum=""
    def dil_ekle(self,yeni_dil):
        self.bildigiDiller.append(yeni_dil)
    
        

In [83]:
ali=veriBilimci()

In [84]:
ali.bildigiDiller

[]

In [85]:
ali.dil_ekle("R")

In [86]:
ali.bildigiDiller

['R']

In [112]:
class Employees(): 
    def __init__(self,FirstName,LastName,Address):
        self.FirstName=FirstName
        self.LastName=LastName
        self.Address=Address
        
class DataScience(Employees):  #(miras)
    def __init__(self,Programming):
        self.Programming=Programming
        
class Marketing(Employees):  #(miras)
    def __init__(self):
        self.StoryTelling=""
        
        
deneme1 = Marketing()
deneme1.StoryTelling

deneme2=DataScience("python")
deneme2.Programming

deneme3=Employees("asli","sesli","caydacira")
deneme3.LastName
        


'sesli'

In [113]:
liste=[1,2,3,4,5,6,7,8]

In [114]:
list(map(lambda x:x%2==0,liste))

[False, True, False, True, False, True, False, True]

In [115]:
list(filter(lambda x:x%2==0,liste))

[2, 4, 6, 8]

In [116]:
from functools import reduce

In [117]:
liste = [1,2,3,4]

In [118]:
reduce(lambda a,b: a+b,liste)

10

In [4]:
A = [1,2,3,4,5]

if type(A) == ():
    print("islem gecersiz")
else:
    print(list(map(lambda x: x/1, A)))

[1.0, 2.0, 3.0, 4.0, 5.0]


In [5]:
fun = lambda x: x**2
fun(3)

9

In [11]:
a = [1,2,3]
list(map(lambda x: x*2, a))

[2, 4, 6]

In [7]:
A = ["ali","veli","isik"]
B = [1,2,3]
AB = [A,B]


for i in AB:
    if type(i[0]) == int:
        print(list(map(lambda x: x-3, i)))

[-2, -1, 0]


In [8]:
A = ["ali","veli","isik"]
B = [1,2,3]
AB = [A,B]

In [9]:
AB

[['ali', 'veli', 'isik'], [1, 2, 3]]

In [12]:
from functools import reduce
reduce(lambda a,b: a+b, ["a","4","a"])

'a4a'

In [13]:
def islem(x,y,z):
    if y == 0:
        print("hatali islem")
    else:
        return x/y*z

In [14]:
islem(1,0,2)

hatali islem


In [15]:
import numpy as np
a = np.array([1,1,1])
b = np.array([2])

a+b

array([3, 3, 3])

In [16]:
list(map(lambda x: x/10, filter(lambda x: x > 20, [10,20,30,40,50])))

[3.0, 4.0, 5.0]

In [17]:
list(map(lambda x: x.upper(), ["Ali","Veli","isik"]))

['ALI', 'VELI', 'ISIK']

In [18]:
A = [[1,2],[3,4],[5,6]]
list(map(lambda x: x[0]*3, A))

[3, 9, 15]

In [19]:
liste = [1,2,3,4]
A = []

for i in liste:
    A.append(i**2)

print(A)

[1, 4, 9, 16]


In [20]:
list(map(lambda x: x**2, liste))

[1, 4, 9, 16]

In [22]:
A = []
for i in ["ali","veli","isik"]:
    A.append(i.replace("i","a"))
print(A)

['ala', 'vela', 'asak']


In [23]:
def yap(x,y,z):
    try:
        print(x/y*z)
    except ZeroDivisionError:
        print("gecersiz islem")

yap(1,2,0)

0.0


In [25]:
list(filter(lambda x: x < 2, [1,2,3,4,5]))

[1]

In [2]:
import numpy as np

In [5]:
a=np.array([1,2,3,4,5,6,7,8,9]).reshape((3,3))

In [6]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [1]:
#fibonacci

In [2]:
a=0
b=1
print(a)
print(b)
while b<10:
    c=a+b
    print(c)
    a=b
    b=c

0
1
1
2
3
5
8
13


In [3]:
a=np.arange(1,50)

In [4]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [5]:
type(a)

numpy.ndarray

In [2]:
kelime1 = "YAPAY"
kelime2 = "zeka"
print(kelime1, kelime2)

YAPAY zeka


In [3]:
x = 0 
while (x < 100):
            x+=2 
print(x) 

100
