In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])
a*b

array([ 3,  8, 15, 24])

In [3]:
type(a)

numpy.ndarray

In [4]:
np.ones((1,3),dtype=int)

array([[1, 1, 1]])

In [6]:
np.zeros((10),dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.full((2,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [9]:
np.arange(0,15,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.linspace(0,1,10)  #0 la 1 arasında 10 tane sayı üret

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [11]:
np.random.normal(10,4,(2,4))

array([[ 6.71113059, 13.1013272 , 11.63472576,  7.73692177],
       [ 9.17621805,  9.81222641,  9.10155554, 13.91224736]])

In [16]:
np.random.randint(0,10,(3,4))

array([[4, 1, 6, 1],
       [7, 7, 8, 2],
       [9, 6, 6, 1]])

In [17]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [18]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [22]:
a = np.array([[1,2,3],[4,5,6]])

In [23]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [24]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [25]:
x = np.array([[1,2,3],[7,8,9]])
y = np.array([[4,5,6],[3,4,5]])

In [28]:
np.concatenate([x,y],axis=1)

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 3, 4, 5]])

In [30]:
k=[4,8,1,23,9]

In [31]:
np.sort(k)

array([ 1,  4,  8,  9, 23])

In [38]:
m=np.random.randint(0,10,(3,4))

In [39]:
m

array([[0, 4, 4, 5],
       [4, 1, 3, 2],
       [5, 8, 5, 9]])

In [40]:
np.sort(m)

array([[0, 4, 4, 5],
       [1, 2, 3, 4],
       [5, 5, 8, 9]])

In [42]:
np.sort(m,axis=0)

array([[0, 1, 3, 2],
       [4, 4, 4, 5],
       [5, 8, 5, 9]])

#*FANCY*

In [46]:
t=np.arange(9).reshape((3,3))

In [44]:
t

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
satir=np.array([0,1])
sutun=np.array([1,2])

In [52]:
t[satir,sutun]

array([1, 5])

In [54]:
t[[0,1],[1,2]] #fancy ile basit index

array([1, 5])

In [100]:
s=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [102]:
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
s[0,0]=10

In [105]:
s

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [106]:
g=np.array([[1,2,3],[{},5,6],[7,8,9]])

In [107]:
g

array([[1, 2, 3],
       [{}, 5, 6],
       [7, 8, 9]], dtype=object)

In [151]:
bos=g[g=={}]

In [152]:
bos

array([{}], dtype=object)

In [155]:
g

array([[1, 2, 3],
       [{}, 5, 6],
       [7, 8, 9]], dtype=object)

In [113]:
bos=[g=={}]

In [114]:
bos

[array([[False, False, False],
        [ True, False, False],
        [False, False, False]])]

In [138]:
f = [1,2,3,4,5]

In [139]:
f

[1, 2, 3, 4, 5]

In [141]:
for i in range(len(f)):
    if f[i]==3:
        f[i]=10

In [142]:
f

[1, 2, 10, 4, 5]

In [143]:
y = [[1,2,3],[4,5,6],[7,8,9]]

In [144]:
y

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [148]:
for i in range(len(y)):
    for j in range(len(y[i])):
        if y[i][j]==4:
            y[i][j]=10

In [149]:
y

[[1, 2, 3], [10, 5, 6], [7, 8, 9]]

In [159]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
t=np.arange(9).reshape((3,3))

In [165]:
t

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [171]:
t[0:1]

array([[0, 1, 2]])

In [174]:
p=np.random.randint(0,10,(3,4))


array([[9, 1, 2, 7],
       [4, 0, 3, 9],
       [2, 0, 2, 7]])

In [175]:
p

array([[9, 1, 2, 7],
       [4, 0, 3, 9],
       [2, 0, 2, 7]])

In [176]:
p[0:1]

array([[9, 1, 2, 7]])

In [181]:
p[2:3]

array([[2, 0, 2, 7]])

In [180]:
v = np.array([7, 3, 4, 7, 0, 9, 3, 2, 9, 2])

v[-2]

9

In [182]:
p[2,3]

7

In [183]:
5*np.array([1,2,3])

array([ 5, 10, 15])

In [184]:
v = np.array([2, 1, 4, 3, 5])

np.sort(v)

array([1, 2, 3, 4, 5])

In [185]:
np.array([3.14, 4,6,1.2])

array([3.14, 4.  , 6.  , 1.2 ])

In [186]:
p[:,2]

array([2, 3, 2])

In [189]:
n=np.random.randint(0,10,(3,5))

In [190]:
n

array([[9, 4, 9, 8, 1],
       [6, 3, 3, 6, 5],
       [0, 0, 3, 8, 5]])

In [191]:
n[:,2]

array([9, 3, 3])

In [192]:
np.random.randint(10, size = (3,2,2))

array([[[8, 6],
        [9, 4]],

       [[3, 7],
        [8, 1]],

       [[6, 0],
        [8, 9]]])

In [193]:
np.random.randint(10, size = (3,3,2))

array([[[6, 8],
        [6, 3],
        [9, 4]],

       [[6, 7],
        [9, 6],
        [7, 0]],

       [[0, 5],
        [6, 9],
        [7, 9]]])

In [194]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [196]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [199]:
v=np.arange(0,30, 3)

In [200]:
[v[1], v[3]]

[3, 9]