In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from keras import models
from keras import layers
from keras.utils import to_categorical

In [3]:
model= models.Sequential()
model.add(layers.Dense(512, activation='relu', input_shape=(4,)))
model.add(layers.Dense(3, activation='softmax'))

In [4]:
model.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

In [5]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [28]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
X.shape

(150, 4)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)

In [25]:
X_train.shape

(105, 4)

In [23]:
y_train

array([1, 1, 0, 2, 1, 2, 0, 0, 0, 2, 2, 0, 0, 1, 1, 2, 0, 0, 2, 1, 0, 2,
       2, 2, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 2, 2, 0, 2, 0, 2, 0,
       2, 1, 0, 2, 1, 2, 1, 0, 1, 2, 1, 2, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2,
       2, 0, 2, 1, 1, 2, 0, 2, 2, 1, 0, 2, 2, 0, 0, 2, 2, 2, 0, 2, 1, 2,
       2, 0, 1, 1, 1, 1, 1, 0, 2, 1, 2, 0, 0, 1, 0, 1, 0])

In [20]:
y.shape

(150,)

In [9]:
train_labels = to_categorical(y_train)
test_labels = to_categorical(y_test)

In [29]:
train_labels

array([[0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0

In [16]:
model.fit(X_train, train_labels, epochs=100, batch_size=4)

Epoch 1/100
3/3 [==============================] - 0s 3ms/step - loss: 0.1206 - accuracy: 0.9810
Epoch 2/100
3/3 [==============================] - 0s 4ms/step - loss: 0.1318 - accuracy: 0.9524
Epoch 3/100
3/3 [==============================] - 0s 2ms/step - loss: 0.1166 - accuracy: 0.9714
Epoch 4/100
3/3 [==============================] - 0s 3ms/step - loss: 0.1189 - accuracy: 0.9619
Epoch 5/100
3/3 [==============================] - 0s 2ms/step - loss: 0.1247 - accuracy: 0.9714
Epoch 6/100
3/3 [==============================] - 0s 4ms/step - loss: 0.1141 - accuracy: 0.9714
Epoch 7/100
3/3 [==============================] - 0s 3ms/step - loss: 0.1155 - accuracy: 0.9714
Epoch 8/100
3/3 [==============================] - 0s 2ms/step - loss: 0.1145 - accuracy: 0.9714
Epoch 9/100
3/3 [==============================] - 0s 2ms/step - loss: 0.1212 - accuracy: 0.9619
Epoch 10/100
3/3 [==============================] - 0s 2ms/step - loss: 0.1054 - accuracy: 0.9810
Epoch 11/100
3/3 [===========

In [17]:
test_loss, test_acc = model.evaluate(X_test, test_labels)

2/2 [==============================] - 0s 4ms/step - loss: 0.0746 - accuracy: 0.9778


In [18]:
print('Test Accuracy: ', test_acc, '\nTest Loss: ', test_loss)

Test Accuracy:  0.9777777791023254 
Test Loss:  0.07455550134181976


In [57]:
veri=np.array([[2.5,2.5,2.5,2.5]])
veri.shape


(1, 4)

In [48]:
veri=veri.reshape(1,4)

In [49]:
veri.shape

(1, 4)

In [39]:
X_train[0].shape

(4,)

In [50]:
prediction=model.predict(veri)

In [51]:
prediction

array([[1.7931375e-08, 5.0019119e-03, 9.9499810e-01]], dtype=float32)

In [52]:
predictionclas=model.predict_classes(veri)

C:\Users\aslisesli\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [53]:
predictionclas

array([2], dtype=int64)

In [62]:
np.save("mnist.npy",X)